### ISSUE TITLE
do we need load any module?

### ISSUE THREAD

**Issue by baturax** [Finamore00/victus-fanboost#2]
even though i load hp-wmi module, it doesnt change the value in /sys/devices/platform/hp-wmi/hwmon/hwmon*/pwm1_enable

**Comment by Finamore00** [comment]
In the various distros I've tried this script on (Fedora, Arch, Tumbleweed) I've never had to load any additional kernel modules. Sorry I can't help you with that one

**Comment by Finamore00** [comment]
In the various distros I've tried this script on (Fedora, Arch, Tumbleweed) I've never had to load any additional kernel modules. Sorry I can't help you with that one
